export const FormatYmd = {
  DD_MM_YYYY: 'DD/MM/yyyy',
  DD_MM_YYYY_STRIKE: 'DD-MM-YYYY',
  YYYYMMDD: 'yyyyMMDD',
  YYYY_MM_DD: 'yyyy/MM/dd',
  YYYY_MM_DD_SLASH: 'YYYY/MM/DD',
  YYYY_MM_DD_DASH: 'yyyy-MM-dd',
  YYYY_MM_DD_STRIKE: 'YYYY-MM-DD',
  YYYY_MMM_DD_2: 'YYYY/MM/DD',
  YYYY_MM_DD_EMPTY: 'YYYYMMDD',
  YYYY_MMM_DD_HH_MM_SS_STRIKE: 'YYYY-MM-DDTHH:mm:ss',
  YYYY_MMM_DD_HH_MM_SS: 'YYYY/MM/DD HH:mm:ss',
  YYYY_MMM_DD_SLASH_HH_MM: 'yyyy/MM/dd HH:mm',
  HH_MM_SS_DD_MM_YYYY: 'HH:mm:ss - DD/MM/YYYY',
  HH_MM: 'HH:mm',
  HH: 'HH',
  MM: 'mm',
  YYYY_MM: 'yyyy-MM',
  YYYY_MM_SLASH: 'yyyy/MM',
  MM_DD: 'MM/DD',
};
